### ISSUE TITLE
Berry Bushes

### ISSUE THREAD

**Issue by orian34** [TotallyNotAScalie/StarlightRiver#18]
- [x] Bush tiles are too high from the ground, look disconnected
![image](https://user-images.githubusercontent.com/12663654/92979750-f5d57b80-f493-11ea-8ce3-e7333ba19e79.png)
- [x] They seem to regrow very fast as well, not even a minute and I gathered 9 berries (from the batch of bushes at the start, 5-7)
- [x] Forest Berries should give a lowered potion sickness instead of 60 seconds for 5 health regained
- [x] regenration and poision
![image](https://user-images.githubusercontent.com/12663654/92979841-3d5c0780-f494-11ea-88fb-4cc6754ba785.png)

**Comment by Steviegt6** [comment]
regenration and poision: Fixed in #24

**Comment by TotallyNotAScalie** [comment]
Fixed
