### ISSUE TITLE
Wind Crystal (Ceiros Expert Drop) does not decrease the cooldown by 16%, it instead increases the cooldown by 32.

### ISSUE THREAD

**Issue by Variable-X** [TotallyNotAScalie/StarlightRiver#2]
It would just be increased by 16, but it is implemented twice, once in CooldownAbility.cs `Cooldown = CooldownMax + CooldownBonus;`, and another in dash.cs `public override int CooldownMax => CooldownBonus + 90;`

**Comment by Dual-Iron** [comment]
Fixed on refactor

**Comment by Variable-X** [comment]
Ok thanks. I should have checked, I was just about to open a pr for that :'(
