### ISSUE TITLE
Issue: Jungle tree vines

### ISSUE THREAD

**Issue by davicslavic42** [TotallyNotAScalie/StarlightRiver#22]
These tests were done on the release day of the test demo and the day after. Single-player, corruption worlds, A new character was made for the initial release of the demo but not for future test worlds. The tree vines that are made for jungle trees can spawn on normal trees if there is a sky island above them; if there was a jungle tree that was generated and then corrupted during world gen there would still be vines on those trees as well. VS statement: I expected to see that the tree vines would only be present on jungle trees; Instead they were able to spawn on purity trees if they were on a sky island, or if the tree was initially a jungle tree then corrupted during world gen the vine would still spawn.

**Comment by TotallyNotAScalie** [comment]
Closing this as this feature has been removed for the forseeable future. May need to be re-opened if we consider re-adding this, but as of now there are now plans to reimplement these
