### ISSUE TITLE
The right Book Altar chest hover icon flickers while frame skip is off

### ISSUE THREAD

**Issue by Variable-X** [TotallyNotAScalie/StarlightRiver#3]
found on Misc.-Earlygame-Content branch
![Flickering Hover Icon](https://user-images.githubusercontent.com/19359968/91640043-d1d05f80-e9e8-11ea-983d-5cd59954392c.gif)

**Comment by Variable-X** [comment]
I think the gif converter I used dropped some of the frames, in reality it flickers a lot faster.

**Comment by TotallyNotAScalie** [comment]
I have my doubts that this is related to this mod at all, can you re-test this after disabling the mod?

**Comment by Variable-X** [comment]
I tried it with the mod disabled and it didn't flicker. However, I thought this was a modded tile when I submitted the issue and now agree that it was probably due to other factors. Sorry for likely wasting your time :(.

**Comment by Dual-Iron** [comment]
![gif](https://user-images.githubusercontent.com/31146412/91645358-6dc29100-ea12-11ea-9cce-e50ade84ef66.gif)
Not reproducible—besides, this trapped chest is from vanilla. Thanks for being attentive though

**Comment by Variable-X** [comment]
Okay, sorry. Is there something more specific I could help with? I feel like I'm just being annoying more than helpful.
